#!/bin/bash

echo "Args:"
echo "    >> [$@]"
echo ""
echo "Env Args:"
echo "    >> [$ENV_ARGS]"
echo ""
echo "Env:"
printenv
echo ""

xrpldconfig=`/bin/cat /config/xrpld.cfg 2>/dev/null | wc -l`
rippledconfig=`/bin/cat /config/rippled.cfg 2>/dev/null | wc -l`
validatorstxt=`/bin/cat /config/validators.txt 2>/dev/null | wc -l`

mkdir -p /config

if [[ "$xrpldconfig" -gt "0" ]]; then
    echo "Existing xrpld config at host /config/xrpld.cfg, using."
    /bin/cat /config/xrpld.cfg > /etc/xrpld/xrpld.cfg
elif [[ "$rippledconfig" -gt "0" ]]; then
    echo "No /config/xrpld.cfg, but found legacy /config/rippled.cfg, using."
    /bin/cat /config/rippled.cfg > /etc/xrpld/xrpld.cfg
fi

if [[ "$validatorstxt" -gt "0" ]]; then
    echo "Existing validator config at host /config/, using."
    /bin/cat /config/validators.txt > /etc/xrpld/validators.txt
fi

# Start xrpld, Passthrough other arguments
exec /usr/bin/xrpld --conf /etc/xrpld/xrpld.cfg $@$ENV_ARGS
